### ISSUE TITLE
Top Tip (email security/privacy)

### ISSUE THREAD

**Issue by nelsonic** [hdrdavies/CV#2]
Hi @hdrdavies! I'm _excited_ to see what you are going to showcase here... :+1: 
I would _advise_ you to have a "public" email address which is **_not**_ your "_primary_" one.
The main reason is so you can protect your identity and finance.
Imagine that bad people get your _primary_ email address and also happen to know what bank you use... they can attempt to send you a "_Phishing_" email to get you to click a link ...
see:
- https://en.wikipedia.org/wiki/Phishing
- https://en.wikipedia.org/wiki/Social_engineering_(security)

Strongly recommend you have a _public_ email which forwards to your _private_ email address and start using [**_aliases**_](https://support.google.com/mail/answer/12096?hl=en) to filter things and **_track how someone found you...**_ :wink:

**Comment by hdrdavies** [comment]
@nelsonic Thanks for the advice! I'll change that now. Do you use your public email on everything except for sensitive things like you mentioned?

**Comment by nelsonic** [comment]
_Maybe_...

**Comment by hdrdavies** [comment]
Know a good way to get a free custom email?

**Comment by nelsonic** [comment]
As in you want huw@davi.es or _something_ like that?

**Comment by hdrdavies** [comment]
you know it

**Comment by nelsonic** [comment]
Do you already have a personal/project domain?
if not: https://iwantmyname.com/ 
then setup an email alias (*which forwards to public gmail for spam filtering)

**Comment by hdrdavies** [comment]
Got me a domain

**Comment by nelsonic** [comment]
Share it once your landing page is up. :+1:

**Comment by nelsonic** [comment]
You've #fixed this. :+1:
